import { byBreakpoints } from './StackProps';

export const DIRECTION_MAPS = {
  row: 'flex-row',
  'row-reverse': 'flex-row-reverse',
  column: 'flex-col',
  'column-reverse': 'flex-col-reverse',
  sm: {
    row: 'sm:flex-row',
    'row-reverse': 'sm:flex-row-reverse',
    column: 'sm:flex-col',
    'column-reverse': 'sm:flex-col-reverse',
  },
  md: {
    row: 'md:flex-row',
    'row-reverse': 'md:flex-row-reverse',
    column: 'md:flex-col',
    'column-reverse': 'md:flex-col-reverse',
  },
  lg: {
    row: 'lg:flex-row',
    'row-reverse': 'lg:flex-row-reverse',
    column: 'lg:flex-col',
    'column-reverse': 'lg:flex-col-reverse',
  },
  xl: {
    row: 'xl:flex-row',
    'row-reverse': 'xl:flex-row-reverse',
    column: 'xl:flex-col',
    'column-reverse': 'xl:flex-col-reverse',
  },
  '2xl': {
    row: '2xl:flex-row',
    'row-reverse': '2xl:flex-row-reverse',
    column: '2xl:flex-col',
    'column-reverse': '2xl:flex-col-reverse',
  },
};

export const JUSTIFY_MAPS = {
  start: 'justify-start',
  center: 'justify-center',
  end: 'justify-end',
  between: 'justify-between',
  around: 'justify-around',
  evenly: 'justify-evenly',
  sm: {
    start: 'sm:justify-start',
    center: 'sm:justify-center',
    end: 'sm:justify-end',
    between: 'sm:justify-between',
    around: 'sm:justify-around',
    evenly: 'sm:justify-evenly',
  },
  md: {
    start: 'md:justify-start',
    center: 'md:justify-center',
    end: 'md:justify-end',
    between: 'md:justify-between',
    around: 'md:justify-around',
    evenly: 'md:justify-evenly',
  },
  lg: {
    start: 'lg:justify-start',
    center: 'lg:justify-center',
    end: 'lg:justify-end',
    between: 'lg:justify-between',
    around: 'lg:justify-around',
    evenly: 'lg:justify-evenly',
  },
  xl: {
    start: 'xl:justify-start',
    center: 'xl:justify-center',
    end: 'xl:justify-end',
    between: 'xl:justify-between',
    around: 'xl:justify-around',
    evenly: 'xl:justify-evenly',
  },
  '2xl': {
    start: '2xl:justify-start',
    center: '2xl:justify-center',
    end: '2xl:justify-end',
    between: '2xl:justify-between',
    around: '2xl:justify-around',
    evenly: '2xl:justify-evenly',
  },
};

export const ALIGN_MAPS = {
  start: 'items-start',
  center: 'items-center',
  end: 'items-end',
  stretch: 'items-stretch',
  baseline: 'items-baseline',
  sm: {
    start: 'sm:items-start',
    center: 'sm:items-center',
    end: 'sm:items-end',
    stretch: 'sm:items-stretch',
    baseline: 'sm:items-baseline',
  },
  md: {
    start: 'md:items-start',
    center: 'md:items-center',
    end: 'md:items-end',
    stretch: 'md:items-stretch',
    baseline: 'md:items-baseline',
  },
  lg: {
    start: 'lg:items-start',
    center: 'lg:items-center',
    end: 'lg:items-end',
    stretch: 'lg:items-stretch',
    baseline: 'lg:items-baseline',
  },
  xl: {
    start: 'xl:items-start',
    center: 'xl:items-center',
    end: 'xl:items-end',
    stretch: 'xl:items-stretch',
    baseline: 'xl:items-baseline',
  },
  '2xl': {
    start: '2xl:items-start',
    center: '2xl:items-center',
    end: '2xl:items-end',
    stretch: '2xl:items-stretch',
    baseline: '2xl:items-baseline',
  },
};

export const SPACING_MAPS = {
  0: 'gap-0',
  px: 'gap-px',
  0.5: 'gap-0.5',
  1: 'gap-1',
  1.5: 'gap-1.5',
  2: 'gap-2',
  2.5: 'gap-2.5',
  3: 'gap-3',
  4: 'gap-4',
  5: 'gap-5',
  6: 'gap-6',
  7: 'gap-7',
  8: 'gap-8',
  9: 'gap-9',
  10: 'gap-10',
  11: 'gap-11',
  12: 'gap-12',
  14: 'gap-14',
  16: 'gap-16',
  20: 'gap-20',
  24: 'gap-24',
  28: 'gap-28',
  32: 'gap-32',
  36: 'gap-36',
  40: 'gap-40',
  44: 'gap-44',
  48: 'gap-48',
  52: 'gap-52',
  56: 'gap-56',
  60: 'gap-60',
  64: 'gap-64',
  72: 'gap-72',
  80: 'gap-80',
  96: 'gap-96',
  sm: {
    0: 'sm:gap-0',
    px: 'sm:gap-px',
    0.5: 'sm:gap-0.5',
    1: 'sm:gap-1',
    1.5: 'sm:gap-1.5',
    2: 'sm:gap-2',
    2.5: 'sm:gap-2.5',
    3: 'sm:gap-3',
    4: 'sm:gap-4',
    5: 'sm:gap-5',
    6: 'sm:gap-6',
    7: 'sm:gap-7',
    8: 'sm:gap-8',
    9: 'sm:gap-9',
    10: 'sm:gap-10',
    11: 'sm:gap-11',
    12: 'sm:gap-12',
    14: 'sm:gap-14',
    16: 'sm:gap-16',
    20: 'sm:gap-20',
    24: 'sm:gap-24',
    28: 'sm:gap-28',
    32: 'sm:gap-32',
    36: 'sm:gap-36',
    40: 'sm:gap-40',
    44: 'sm:gap-44',
    48: 'sm:gap-48',
    52: 'sm:gap-52',
    56: 'sm:gap-56',
    60: 'sm:gap-60',
    64: 'sm:gap-64',
    72: 'sm:gap-72',
    80: 'sm:gap-80',
    96: 'sm:gap-96',
  },
  md: {
    0: 'md:gap-0',
    px: 'md:gap-px',
    0.5: 'md:gap-0.5',
    1: 'md:gap-1',
    1.5: 'md:gap-1.5',
    2: 'md:gap-2',
    2.5: 'md:gap-2.5',
    3: 'md:gap-3',
    4: 'md:gap-4',
    5: 'md:gap-5',
    6: 'md:gap-6',
    7: 'md:gap-7',
    8: 'md:gap-8',
    9: 'md:gap-9',
    10: 'md:gap-10',
    11: 'md:gap-11',
    12: 'md:gap-12',
    14: 'md:gap-14',
    16: 'md:gap-16',
    20: 'md:gap-20',
    24: 'md:gap-24',
    28: 'md:gap-28',
    32: 'md:gap-32',
    36: 'md:gap-36',
    40: 'md:gap-40',
    44: 'md:gap-44',
    48: 'md:gap-48',
    52: 'md:gap-52',
    56: 'md:gap-56',
    60: 'md:gap-60',
    64: 'md:gap-64',
    72: 'md:gap-72',
    80: 'md:gap-80',
    96: 'md:gap-96',
  },
  lg: {
    0: 'lg:gap-0',
    px: 'lg:gap-px',
    0.5: 'lg:gap-0.5',
    1: 'lg:gap-1',
    1.5: 'lg:gap-1.5',
    2: 'lg:gap-2',
    2.5: 'lg:gap-2.5',
    3: 'lg:gap-3',
    4: 'lg:gap-4',
    5: 'lg:gap-5',
    6: 'lg:gap-6',
    7: 'lg:gap-7',
    8: 'lg:gap-8',
    9: 'lg:gap-9',
    10: 'lg:gap-10',
    11: 'lg:gap-11',
    12: 'lg:gap-12',
    14: 'lg:gap-14',
    16: 'lg:gap-16',
    20: 'lg:gap-20',
    24: 'lg:gap-24',
    28: 'lg:gap-28',
    32: 'lg:gap-32',
    36: 'lg:gap-36',
    40: 'lg:gap-40',
    44: 'lg:gap-44',
    48: 'lg:gap-48',
    52: 'lg:gap-52',
    56: 'lg:gap-56',
    60: 'lg:gap-60',
    64: 'lg:gap-64',
    72: 'lg:gap-72',
    80: 'lg:gap-80',
    96: 'lg:gap-96',
  },
  xl: {
    0: 'xl:gap-0',
    px: 'xl:gap-px',
    0.5: 'xl:gap-0.5',
    1: 'xl:gap-1',
    1.5: 'xl:gap-1.5',
    2: 'xl:gap-2',
    2.5: 'xl:gap-2.5',
    3: 'xl:gap-3',
    4: 'xl:gap-4',
    5: 'xl:gap-5',
    6: 'xl:gap-6',
    7: 'xl:gap-7',
    8: 'xl:gap-8',
    9: 'xl:gap-9',
    10: 'xl:gap-10',
    11: 'xl:gap-11',
    12: 'xl:gap-12',
    14: 'xl:gap-14',
    16: 'xl:gap-16',
    20: 'xl:gap-20',
    24: 'xl:gap-24',
    28: 'xl:gap-28',
    32: 'xl:gap-32',
    36: 'xl:gap-36',
    40: 'xl:gap-40',
    44: 'xl:gap-44',
    48: 'xl:gap-48',
    52: 'xl:gap-52',
    56: 'xl:gap-56',
    60: 'xl:gap-60',
    64: 'xl:gap-64',
    72: 'xl:gap-72',
    80: 'xl:gap-80',
    96: 'xl:gap-96',
  },
  '2xl': {
    0: '2xl:gap-0',
    px: '2xl:gap-px',
    0.5: '2xl:gap-0.5',
    1: '2xl:gap-1',
    1.5: '2xl:gap-1.5',
    2: '2xl:gap-2',
    2.5: '2xl:gap-2.5',
    3: '2xl:gap-3',
    4: '2xl:gap-4',
    5: '2xl:gap-5',
    6: '2xl:gap-6',
    7: '2xl:gap-7',
    8: '2xl:gap-8',
    9: '2xl:gap-9',
    10: '2xl:gap-10',
    11: '2xl:gap-11',
    12: '2xl:gap-12',
    14: '2xl:gap-14',
    16: '2xl:gap-16',
    20: '2xl:gap-20',
    24: '2xl:gap-24',
    28: '2xl:gap-28',
    32: '2xl:gap-32',
    36: '2xl:gap-36',
    40: '2xl:gap-40',
    44: '2xl:gap-44',
    48: '2xl:gap-48',
    52: '2xl:gap-52',
    56: '2xl:gap-56',
    60: '2xl:gap-60',
    64: '2xl:gap-64',
    72: '2xl:gap-72',
    80: '2xl:gap-80',
    96: '2xl:gap-96',
  },
};

export const mapPropToClassnames = (
  prop: string | number | Record<any, any>,
  map: Record<any, any>
): string => {
  if (typeof prop === 'string' || typeof prop === 'number') {
    return map[prop];
  } else {
    const defaultClassname = map[prop.default];

    const entriesWithoutDefault = Object.entries(prop).filter(
      ([key]) => key !== 'default'
    );

    const breakpointClassnames = entriesWithoutDefault.map(
      ([userBreakpoint, userProp]) => {
        const classesForUserBreakpoint =
          map[userBreakpoint as keyof typeof map];

        return classesForUserBreakpoint[
          userProp as keyof typeof classesForUserBreakpoint
        ] as string;
      }
    );

    const classnames = [defaultClassname, ...breakpointClassnames];
    classnames.sort(byBreakpoints);

    return classnames.join(' ');
  }
};
